### ISSUE TITLE
Cursor.cs and future development

### ISSUE THREAD

**Issue by zolastro** [Sothe5/FireEmblemBlazingSword#1]
I've just noticed this file in your project. I've been wondering for a while if I could make some kind of refactorization of this code to keep it simple and smaller.

I'll also would like to ask if this project is dead or I could start colaborating with you. I'm not a huge fan of the saga, but still I'll be glad to help!

Greetings,

David

**Comment by Sothe5** [comment]
If you would like to refactor the code is totally fine for me but put a counter with the hours wasted on that task buddy :P 
About working with me, sorry but this was kind of a challenge to my own so the code is not too explanatory.

**Comment by zolastro** [comment]
Don't worry, I'm strong minded and I'll take it as a challenge ;)
